//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---------------------------------------------------------------------------
// ClusterCapabilities
// ---------------------------------------------------------------------------

func (in *ClusterCapabilities) DeepCopyInto(out *ClusterCapabilities) {
	*out = *in
}

func (in *ClusterCapabilities) DeepCopy() *ClusterCapabilities {
	if in == nil {
		return nil
	}
	out := new(ClusterCapabilities)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// CostProfile
// ---------------------------------------------------------------------------

func (in *CostProfile) DeepCopyInto(out *CostProfile) {
	*out = *in
}

func (in *CostProfile) DeepCopy() *CostProfile {
	if in == nil {
		return nil
	}
	out := new(CostProfile)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ClusterCapacityStatus
// ---------------------------------------------------------------------------

func (in *ClusterCapacityStatus) DeepCopyInto(out *ClusterCapacityStatus) {
	*out = *in
}

func (in *ClusterCapacityStatus) DeepCopy() *ClusterCapacityStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ClusterProfileSpec
// ---------------------------------------------------------------------------

func (in *ClusterProfileSpec) DeepCopyInto(out *ClusterProfileSpec) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(ClusterCapabilities)
		**out = **in
	}
	if in.CostProfile != nil {
		in, out := &in.CostProfile, &out.CostProfile
		*out = new(CostProfile)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ClusterProfileSpec) DeepCopy() *ClusterProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ClusterProfileStatus
// ---------------------------------------------------------------------------

func (in *ClusterProfileStatus) DeepCopyInto(out *ClusterProfileStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(ClusterCapacityStatus)
		**out = **in
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = new(v1.Time)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterProfileStatus) DeepCopy() *ClusterProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ClusterProfile
// ---------------------------------------------------------------------------

func (in *ClusterProfile) DeepCopyInto(out *ClusterProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterProfile) DeepCopy() *ClusterProfile {
	if in == nil {
		return nil
	}
	out := new(ClusterProfile)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------------------------------------------------------------------
// ClusterProfileList
// ---------------------------------------------------------------------------

func (in *ClusterProfileList) DeepCopyInto(out *ClusterProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterProfileList) DeepCopy() *ClusterProfileList {
	if in == nil {
		return nil
	}
	out := new(ClusterProfileList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------------------------------------------------------------------
// TrafficShiftingSpec
// ---------------------------------------------------------------------------

func (in *TrafficShiftingSpec) DeepCopyInto(out *TrafficShiftingSpec) {
	*out = *in
	if in.ClusterSelector != nil {
		in, out := &in.ClusterSelector, &out.ClusterSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TrafficShiftingSpec) DeepCopy() *TrafficShiftingSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficShiftingSpec)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ClusterLifecycleSpec
// ---------------------------------------------------------------------------

func (in *ClusterLifecycleSpec) DeepCopyInto(out *ClusterLifecycleSpec) {
	*out = *in
	if in.ExcludedClusters != nil {
		in, out := &in.ExcludedClusters, &out.ExcludedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ClusterLifecycleSpec) DeepCopy() *ClusterLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// CrossClusterConstraint
// ---------------------------------------------------------------------------

func (in *CrossClusterConstraint) DeepCopyInto(out *CrossClusterConstraint) {
	*out = *in
	if in.RequiredRegions != nil {
		in, out := &in.RequiredRegions, &out.RequiredRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ForbiddenProviders != nil {
		in, out := &in.ForbiddenProviders, &out.ForbiddenProviders
		*out = make([]CloudProvider, len(*in))
		copy(*out, *in)
	}
}

func (in *CrossClusterConstraint) DeepCopy() *CrossClusterConstraint {
	if in == nil {
		return nil
	}
	out := new(CrossClusterConstraint)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// GlobalPolicySpec
// ---------------------------------------------------------------------------

func (in *GlobalPolicySpec) DeepCopyInto(out *GlobalPolicySpec) {
	*out = *in
	if in.TrafficShifting != nil {
		in, out := &in.TrafficShifting, &out.TrafficShifting
		*out = new(TrafficShiftingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterLifecycle != nil {
		in, out := &in.ClusterLifecycle, &out.ClusterLifecycle
		*out = new(ClusterLifecycleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CrossClusterConstraints != nil {
		in, out := &in.CrossClusterConstraints, &out.CrossClusterConstraints
		*out = make([]CrossClusterConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GlobalPolicySpec) DeepCopy() *GlobalPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// GlobalPolicyStatus
// ---------------------------------------------------------------------------

func (in *GlobalPolicyStatus) DeepCopyInto(out *GlobalPolicyStatus) {
	*out = *in
	if in.LastOptimizationTime != nil {
		in, out := &in.LastOptimizationTime, &out.LastOptimizationTime
		*out = new(v1.Time)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GlobalPolicyStatus) DeepCopy() *GlobalPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// GlobalPolicy
// ---------------------------------------------------------------------------

func (in *GlobalPolicy) DeepCopyInto(out *GlobalPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GlobalPolicy) DeepCopy() *GlobalPolicy {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------------------------------------------------------------------
// GlobalPolicyList
// ---------------------------------------------------------------------------

func (in *GlobalPolicyList) DeepCopyInto(out *GlobalPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GlobalPolicyList) DeepCopy() *GlobalPolicyList {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *GlobalPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
