apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cluster-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
