//go:build !ignore_autogenerated

// Copyright 2024 OptiPilot AI Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FairSharePolicy) DeepCopyInto(out *FairSharePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FairSharePolicy.
func (in *FairSharePolicy) DeepCopy() *FairSharePolicy {
	if in == nil {
		return nil
	}
	out := new(FairSharePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantBudgets) DeepCopyInto(out *TenantBudgets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantBudgets.
func (in *TenantBudgets) DeepCopy() *TenantBudgets {
	if in == nil {
		return nil
	}
	out := new(TenantBudgets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfile) DeepCopyInto(out *TenantProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfile.
func (in *TenantProfile) DeepCopy() *TenantProfile {
	if in == nil {
		return nil
	}
	out := new(TenantProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileList) DeepCopyInto(out *TenantProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileList.
func (in *TenantProfileList) DeepCopy() *TenantProfileList {
	if in == nil {
		return nil
	}
	out := new(TenantProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileSpec) DeepCopyInto(out *TenantProfileSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Budgets != nil {
		in, out := &in.Budgets, &out.Budgets
		*out = new(TenantBudgets)
		**out = **in
	}
	if in.FairSharePolicy != nil {
		in, out := &in.FairSharePolicy, &out.FairSharePolicy
		*out = new(FairSharePolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileSpec.
func (in *TenantProfileSpec) DeepCopy() *TenantProfileSpec {
	if in == nil {
		return nil
	}
	out := new(TenantProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantProfileStatus) DeepCopyInto(out *TenantProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantProfileStatus.
func (in *TenantProfileStatus) DeepCopy() *TenantProfileStatus {
	if in == nil {
		return nil
	}
	out := new(TenantProfileStatus)
	in.DeepCopyInto(out)
	return out
}
