//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---------------------------------------------------------------------------
// ApplicationTuning
// ---------------------------------------------------------------------------

func (in *ApplicationTuning) DeepCopyInto(out *ApplicationTuning) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ApplicationTuning) DeepCopy() *ApplicationTuning {
	if in == nil {
		return nil
	}
	out := new(ApplicationTuning)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationTuning) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------------------------------------------------------------------
// ApplicationTuningList
// ---------------------------------------------------------------------------

func (in *ApplicationTuningList) DeepCopyInto(out *ApplicationTuningList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationTuning, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ApplicationTuningList) DeepCopy() *ApplicationTuningList {
	if in == nil {
		return nil
	}
	out := new(ApplicationTuningList)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationTuningList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------------------------------------------------------------------
// ApplicationTuningSpec
// ---------------------------------------------------------------------------

func (in *ApplicationTuningSpec) DeepCopyInto(out *ApplicationTuningSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]TunableParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OptimizationTarget = in.OptimizationTarget
	if in.SafetyPolicy != nil {
		in, out := &in.SafetyPolicy, &out.SafetyPolicy
		*out = new(TuningSafetyPolicy)
		**out = **in
	}
}

func (in *ApplicationTuningSpec) DeepCopy() *ApplicationTuningSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationTuningSpec)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ApplicationTuningStatus
// ---------------------------------------------------------------------------

func (in *ApplicationTuningStatus) DeepCopyInto(out *ApplicationTuningStatus) {
	*out = *in
	if in.CurrentValues != nil {
		in, out := &in.CurrentValues, &out.CurrentValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BestValues != nil {
		in, out := &in.BestValues, &out.BestValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Observations != nil {
		in, out := &in.Observations, &out.Observations
		*out = make([]ParameterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastOptimizationTime != nil {
		in, out := &in.LastOptimizationTime, &out.LastOptimizationTime
		*out = (*in).DeepCopy()
	}
	if in.NextOptimizationTime != nil {
		in, out := &in.NextOptimizationTime, &out.NextOptimizationTime
		*out = (*in).DeepCopy()
	}
	if in.CooldownUntil != nil {
		in, out := &in.CooldownUntil, &out.CooldownUntil
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ApplicationTuningStatus) DeepCopy() *ApplicationTuningStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationTuningStatus)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ConfigMapRef
// ---------------------------------------------------------------------------

func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// OptimizationTarget
// ---------------------------------------------------------------------------

func (in *OptimizationTarget) DeepCopyInto(out *OptimizationTarget) {
	*out = *in
}

func (in *OptimizationTarget) DeepCopy() *OptimizationTarget {
	if in == nil {
		return nil
	}
	out := new(OptimizationTarget)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// ParameterObservation
// ---------------------------------------------------------------------------

func (in *ParameterObservation) DeepCopyInto(out *ParameterObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

func (in *ParameterObservation) DeepCopy() *ParameterObservation {
	if in == nil {
		return nil
	}
	out := new(ParameterObservation)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// TunableParameter
// ---------------------------------------------------------------------------

func (in *TunableParameter) DeepCopyInto(out *TunableParameter) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.AllowedValues != nil {
		in, out := &in.AllowedValues, &out.AllowedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *TunableParameter) DeepCopy() *TunableParameter {
	if in == nil {
		return nil
	}
	out := new(TunableParameter)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// TuningTargetRef
// ---------------------------------------------------------------------------

func (in *TuningTargetRef) DeepCopyInto(out *TuningTargetRef) {
	*out = *in
}

func (in *TuningTargetRef) DeepCopy() *TuningTargetRef {
	if in == nil {
		return nil
	}
	out := new(TuningTargetRef)
	in.DeepCopyInto(out)
	return out
}

// ---------------------------------------------------------------------------
// TuningSafetyPolicy
// ---------------------------------------------------------------------------

func (in *TuningSafetyPolicy) DeepCopyInto(out *TuningSafetyPolicy) {
	*out = *in
}

func (in *TuningSafetyPolicy) DeepCopy() *TuningSafetyPolicy {
	if in == nil {
		return nil
	}
	out := new(TuningSafetyPolicy)
	in.DeepCopyInto(out)
	return out
}
